import{a as v,i as d,S as M}from"./assets/vendor-550cebad.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();async function f(r,t){const l="https://pixabay.com/api/",s={key:"43045926-d10eb038526040017b5fd39ad",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await v.get(l,{params:s})).data}function m(r){if(document.querySelector(".gallery-img"),r.length===0){d.info({title:"Info",color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const t=r.map(({webformatURL:s,largeImageURL:e,tags:o,likes:i,views:L,comments:w,downloads:q})=>`<a href="${e}" class="gallery-item" data-lightbox="gallery">
    <img src="${s}" alt="${o}" />
    <div class="info">
      <p><strong>Likes:</strong> ${i}</p>
      <p><strong>Views:</strong> ${L}</p>
      <p><strong>Comments:</strong> ${w}</p>
      <p><strong>Downloads:</strong> ${q}</p>
    </div>
  </a>`).join("");n.gallery.insertAdjacentHTML("beforeend",t),new M(".gallery-item",{captionsData:"alt"}).refresh()}let a=1,c,p=0;const S=15,n={form:document.querySelector(".form"),input:document.getElementById("query"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery-img"),btnMore:document.querySelector(".btn-load-more")};n.form.addEventListener("submit",x);n.btnMore.addEventListener("click",O);function P(){n.btnMore.classList.remove("is-hidden")}function g(){n.btnMore.classList.add("is-hidden")}function u(){n.loader.classList.add("is-hidden")}function h(){n.loader.classList.remove("is-hidden")}u();g();async function x(r){if(r.preventDefault(),h(),c=n.input.value.trim(),a=1,n.gallery.innerHTML="",!c){d.error({message:"Please enter a request",position:"topRight"}),g(),b();return}try{const t=await f(c,a);if(t.hits.length===0){u(),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p=Math.ceil(t.totalHits/S),m(t.hits)}catch(t){console.log(t)}u(),y(),n.form.reset()}async function O(){a+=1,h();try{const r=await f(c,a);m(r.hits)}catch(r){console.log(r)}b(),y(),u()}function y(){a>=p?(g(),d.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"yellow"})):P()}function b(){const r=n.gallery.firstChild.getBoundingClientRect().height,t=window.pageYOffset||document.documentElement.scrollTop;window.scroll({top:t+r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
